name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Login to Yandex.Cloud Container Registry
        uses: docker/login-action@v1 
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YC_OAUTH }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          # Tags set YC_CR_ID
          tags: |
            ghcr.io/pilprod/web-pilprod:latest
            ghcr.io/pilprod/web-pilprod:1.0.0
            cr.yandex/crpl0u6n26tru58eva57/web-pilprod:latest
            cr.yandex/crpl0u6n26tru58eva57/web-pilprod:1.0.0
